# Generated by Django 4.2.6 on 2023-10-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='apelido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
