# Generated by Django 4.2.6 on 2023-10-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_agenda_apelido_alter_agenda_complemento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Contato',
        ),
    ]
