# Generated by Django 4.2.6 on 2023-10-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0003_rename_agenda_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoa'},
        ),
    ]
