# Generated by Django 4.2.7 on 2023-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0006_alter_contato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cidade',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('CL', 'Campo Limpo'), ('BA', 'Bauru'), ('CP', 'Campinas')], max_length=2, null=True),
        ),
    ]
