# Generated by Django 4.2.7 on 2023-11-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0007_alter_contato_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('UF', models.CharField(choices=[('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
    ]
